version: "3.9"
services:
  app_dev:
    container_name: app_dev
    restart: always
    build: 
      context: ./container_app/
      dockerfile: Dockerfile.dev
    image: app_dev:1.0
  nginx_dev:
    environment:
     - NGINX_SERVER_ADDRESS=$NGINX_SERVER_ADDRESS
     - NGINX_LOCATION=$NGINX_LOCATION
     - NGINX_LOCATION_PORT=$NGINX_LOCATION_PORT
    container_name: nginx_dev
    restart: always
    build: 
      context: ./container_app/nginx/
      dockerfile: Dockerfile
    image: nginx_dev:1.0
    ports:
      - "5000:80"
    depends_on:
      - app_dev
