version: "3.9"
services:
  app_prod:
    restart: always
    build: 
      context: ./container_app/
      dockerfile: Dockerfile.prod
    image: app_prod:1.0
  nginx_prod:
    environment:
     - NGINX_SERVER_ADDRESS=$NGINX_SERVER_ADDRESS
     - NGINX_LOCATION=$NGINX_LOCATION
     - NGINX_LOCATION_PORT=$NGINX_LOCATION_PORT
    restart: always
    build: 
      context: ./container_app/nginx/
      dockerfile: Dockerfile
    image: nginx_prod:1.0
    ports:
      - "8600:80"
    depends_on:
      - app_prod
